(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(Man-notify-method 'bully)
 '(TeX-macro-global
   '("/var/lib/texmf/tex/" "/usr/share/texlive/texmf-dist/tex/" "/usr/share/texlive/texmf-dist/bibtex/bst/" "/usr/share/texmf/tex/" "~/texmf"))
 '(abbrev-file-name "/home/rgr/.emacs.d/etc/abbrev/abbrev.el")
 '(ag-arguments '("--smart-case" "--stats" "--multiline" "-U"))
 '(ag-ignore-list '("value" "cache" "log" "data"))
 '(alert-default-style 'libnotify nil nil "Customized with use-package alert")
 '(alert-fade-time 15)
 '(apropos-do-all t)
 '(async-shell-command-buffer 'confirm-kill-process)
 '(auth-sources '("~/.gnupg/auth/authinfo.gpg" "~/.gnupg/auth/authirc.gpg"))
 '(auto-save-interval 30)
 '(bbdb-complete-mail-allow-cycling t)
 '(bbdb-complete-name-allow-cycling t t)
 '(bbdb-file "~/.bbdb" t)
 '(blink-cursor-interval 0.2)
 '(bmkp-bmenu-commands-file "/home/rgr/.emacs.d/var/secrets/bmkp/bmenu-commands.el" t)
 '(bmkp-last-as-first-bookmark-file nil)
 '(bookmark-default-file "~/.emacs.d/var/secrets/bmkp/current-bookmark.el")
 '(bookmark-save-flag 1)
 '(bookmark-version-control 'nospecial)
 '(browse-url-browser-function 'eww-browse-url)
 '(browse-url-generic-program "google-chrome")
 '(browse-url-secondary-browser-function 'browse-url-firefox)
 '(c-default-style
   '((c-mode . "k&r") (c++-mode . "k&r") (java-mode . "java") (awk-mode . "awk") (other . "gnu")))
 '(calendar-mark-diary-entries-flag t)
 '(calendar-view-diary-initially-flag t)
 '(canlock-password "106923df36ef41eb263045249a447dac2d49649a")
 '(ccls-code-lens-position 'inplace)
 '(ccls-initialization-options '(request: (timeout:5000)))
 '(ccls-root-files '(".ccls-root" ".projectile"))
 '(ccls-sem-highlight-method 'overlay)
 '(centaur-tabs-cycle-scope 'tabs)
 '(clang-format-style "LLVM")
 '(clean-buffer-list-delay-general 1)
 '(company-box-doc-no-wrap t)
 '(company-tooltip-maximum-width 64)
 '(compilation-ask-about-save nil)
 '(compilation-error-regexp-alist
   '(bash-xset-x dotnet-warning dotnet-error msbuild-warning msbuild-error xbuild-warning xbuild-error dotnet-testfail typescript-nglint-warning typescript-nglint-error typescript-tslint typescript-tsc-pretty typescript-tsc absoft ada aix ant bash borland
                 python-tracebacks-and-caml cmake cmake-info comma cucumber msft edg-1 edg-2 epc ftnchek gradle-kotlin iar ibm irix java jikes-file maven jikes-line clang-include gcc-include ruby-Test::Unit gmake gnu lcc makepp mips-1 mips-2 omake oracle
                 perl php rxp sparc-pascal-file sparc-pascal-line sparc-pascal-example sun sun-ada watcom 4bsd gcov-file gcov-header gcov-nomark gcov-called-line gcov-never-called perl--Pod::Checker perl--Test perl--Test2 perl--Test::Harness weblint
                 guile-file guile-line))
 '(compilation-message-face 'default)
 '(confirm-kill-processes nil)
 '(confirm-nonexistent-file-or-buffer nil)
 '(cua-keep-region-after-copy nil)
 '(cursor-type 'box)
 '(custom-safe-themes
   '("d6da24347c813d1635a217d396cf1e3be26484fd4d05be153f3bd2b293d2a0b5" "0568a5426239e65aab5e7c48fa1abde81130a87ddf7f942613bf5e13bf79686b" "2b502f6e3bf0cba42fe7bf83a000f2d358a7020a7780a8682fcfed0c9dbffb5f"
     "076ee9f2c64746aac7994b697eb7dbde23ac22988d41ef31b714fc6478fee224" "8ca8fbaeaeff06ac803d7c42de1430b9765d22a439efc45b5ac572c2d9d09b16" "7b3ce93a17ce4fc6389bba8ecb9fee9a1e4e01027a5f3532cc47d160fe303d5a"
     "972d69a06b8f6e5d43fb83ff59417511f09ba1a1783aab5e22c0e9cbd25ad458" "d234fa6da0282c254f00d534079374d1c6f3c3e600075bc65fe661fdd1947792" "7d6861c031212fca9b4a963ced6230be2aa3139570b85ea5e77619b1fd0351ad"
     "9b39b25c3a23b1be6e99a3648b91ebaf2a7efdde236e3472aa95f1708ec61d4f" "3f1dcd824a683e0ab194b3a1daac18a923eed4dba5269eecb050c718ab4d5a26" default))
 '(dap-chrome-debug-program
   '("node" "/home/rgr/.emacs.d/var/dap/extensions/vscode/msjsdiag.debugger-for-chrome/out/src/chromeDebug.js"))
 '(dap-default-terminal-kind "external")
 '(dap-external-terminal
   '("alacritty" "-t" "{display}" "-e" "zsh" "-c" "exec {command}"))
 '(dap-gdb-lldb-debug-program
   '("node" "/home/rgr/.vscode/extensions/webfreak.debug-0.25.0/out/src/lldb.js"))
 '(dap-gdb-lldb-path
   "/home/rgr/.vscode/extensions/webfreak.debug-0.25.0/vscode/webfreak.debug")
 '(dap-internal-terminal 'dap-internal-terminal-auto)
 '(dap-print-io t)
 '(dap-ui-controls-mode t)
 '(dap-utils-extension-path "/home/rgr/.vscode/extensions/webfreak.debug-0.25.0" t)
 '(delete-active-region 'kill)
 '(delete-old-versions t)
 '(delete-selection-mode t)
 '(desktop-globals-to-save
   '(desktop-missing-file-warning tags-file-name tags-table-list search-ring regexp-search-ring register-alist file-name-history extended-command-history minibuffer-history))
 '(desktop-lazy-idle-delay 10000)
 '(desktop-load-locked-desktop t)
 '(desktop-locals-to-save nil)
 '(desktop-restore-eager 8)
 '(desktop-save t)
 '(diary-file "~/.diary")
 '(diary-list-include-blanks t)
 '(diary-mark-entries-hook '(diary-mark-included-diary-files))
 '(diary-number-of-entries 7)
 '(dictionary-server "localhost" nil nil "Customized with use-package dictionary")
 '(diredp-hide-details-initially-flag nil)
 '(display-buffer-alist
   '(("\\*Symfony Web Server\\*.*" display-buffer-no-window) (popwin:display-buffer-condition popwin:display-buffer-action)))
 '(display-time-mode t)
 '(eat-exit-hook nil)
 '(eglot-extend-to-xref t)
 '(el-docstring-sap--display-func 'el-docstring-sap--quick-peek)
 '(elpy-formatter 'autopep8)
 '(elscreen-display-tab nil)
 '(enable-recursive-minibuffers t)
 '(epa-file-cache-passphrase-for-symmetric-encryption nil)
 '(erc-autojoin-channels-alist
   '((Libera.Chat "#rust" "#linux" "#emacs" "#sway" "#debian")))
 '(erc-autojoin-delay 1)
 '(erc-autojoin-domain-only nil)
 '(erc-autojoin-mode t)
 '(erc-autojoin-timing 'ident)
 '(erc-buffer-display 'bury)
 '(erc-fill-column 128)
 '(erc-fill-function 'erc-fill-static)
 '(erc-fill-mode t)
 '(erc-fill-static-center 1)
 '(erc-header-line-format "")
 '(erc-hide-list '("353" "JOIN" "KICK" "NICK" "PART" "QUIT" "MODE"))
 '(erc-hide-timestamps nil)
 '(erc-input-line-position nil)
 '(erc-insert-timestamp-function 'erc-insert-timestamp-left)
 '(erc-interactive-display 'window-noselect)
 '(erc-kill-buffer-on-part t)
 '(erc-kill-queries-on-quit t)
 '(erc-kill-server-buffer-on-quit t)
 '(erc-match-mode t)
 '(erc-max-buffer-size 20000)
 '(erc-minibuffer-notice nil)
 '(erc-modules
   '(autojoin button completion fill irccontrols list match menu move-to-prompt netsplit networks noncommands readonly ring stamp track))
 '(erc-nick-uniquifier "_DUP")
 '(erc-notice-highlight-type 'prefix)
 '(erc-notifications-mode t)
 '(erc-pcomplete-mode t)
 '(erc-prompt "#>")
 '(erc-prompt-for-nickserv-password nil)
 '(erc-prompt-for-password nil)
 '(erc-scrolltobottom-mode nil)
 '(erc-server-auto-reconnect t)
 '(erc-server-reconnect-attempts t)
 '(erc-stamp-mode t)
 '(erc-startup-file-list nil)
 '(erc-system-name nil)
 '(erc-timestamp-format "[%T]")
 '(erc-timestamp-format-right nil)
 '(erc-timestamp-only-if-changed-flag nil)
 '(erc-track-enable-keybindings nil)
 '(erc-track-exclude '("324" "332" "333" "353" "329"))
 '(erc-track-exclude-types
   '("JOIN" "NICK" "PART" "QUIT" "MODE" "324" "329" "332" "333" "353" "477"))
 '(erc-truncate-buffer-on-save t)
 '(erc-try-new-nick-p t)
 '(erc-user-mode nil)
 '(erc-whowas-on-nosuchnick t)
 '(eshell-banner-message
   "\12W.O.P.R Online...\12Syncing. Please Wait.\12\12Greetings Professor Falken.\12Would you like to play a game?\12\12")
 '(eshell-hist-ignoredups t)
 '(eshell-history-size nil)
 '(eval-expression-print-length nil)
 '(eww-download-directory "~/Downloads")
 '(eww-search-prefix "https://google.com/search?q=")
 '(expand-region-smart-cursor t)
 '(f 'el-docstring-sap--display)
 '(fci-rule-color "#14151E" t)
 '(fill-column 256)
 '(gdb-display-io-nopopup t)
 '(gdb-many-windows t)
 '(gdb-show-main t)
 '(gdscript-docs-local-path
   "/home/rgr/Documents/Programming/Godot/www/docs.godotengine.org/en/stable")
 '(gdscript-docs-use-eww nil)
 '(geben-dbgp-default-port 8000)
 '(git-gutter:update-interval 2)
 '(global-mark-ring-max 64)
 '(google-translate-default-source-language "de")
 '(google-translate-default-target-language "en")
 '(grep-find-ignored-directories
   '("SCCS" "RCS" "CVS" "MCVS" ".src" ".svn" ".git" ".hg" ".bzr" "_MTN" "_darcs" "{arch}" "var" "cache"))
 '(gud-tooltip-modes
   '(gud-mode c-mode c++-mode fortran-mode python-mode emacs-lisp-mode))
 '(haskell-process-auto-import-loaded-modules t)
 '(haskell-process-log t)
 '(haskell-process-path-cabal "~/.ghcup/bin/cabal")
 '(haskell-process-suggest-remove-import-lines t)
 '(helpful-max-buffers nil)
 '(history-delete-duplicates t)
 '(indent-tabs-mode nil)
 '(indium-chrome-executable "google-chrome")
 '(inhibit-startup-screen t)
 '(ispell-dictionary nil)
 '(ispell-local-dictionary "british")
 '(ispell-program-name "/usr/bin/aspell")
 '(ispell-query-replace-choices t)
 '(ispell-silently-savep t)
 '(kept-new-versions 20)
 '(large-file-warning-threshold nil)
 '(lsp-diagnostics-provider :flymake)
 '(lsp-keymap-prefix "C-c l")
 '(lsp-tcp-connection-timeout 5)
 '(lsp-ui-doc-delay 0.25)
 '(lsp-ui-doc-header t)
 '(lsp-ui-doc-position 'bottom)
 '(lsp-ui-doc-show-with-cursor t)
 '(lsp-ui-doc-use-webkit t)
 '(lsp-ui-sideline-delay 2)
 '(lsp-ui-sideline-show-code-actions t)
 '(lsp-ui-sideline-show-hover t)
 '(magit-bury-buffer-function 'magit-restore-window-configuration)
 '(max-lisp-eval-depth 32000)
 '(mu4e-compose-signature '(concat "" "https://github.com/rileyrg?tab=repositories"))
 '(mu4e-search-include-related nil nil nil "Customized with use-package mu4e")
 '(mu4e-search-threads nil nil nil "Customized with use-package mu4e")
 '(org-M-RET-may-split-line nil nil nil "Customized with use-package org")
 '(org-agenda-custom-commands
   '(("n" "Agenda and all TODOs" ((agenda "" nil) (alltodo "" nil)) nil)))
 '(org-agenda-skip-deadline-if-done t)
 '(org-agenda-skip-scheduled-if-deadline-is-shown t nil nil "Customized with use-package org")
 '(org-agenda-skip-scheduled-if-done t)
 '(org-agenda-start-on-weekday 0 nil nil "Customized with use-package org")
 '(org-babel-load-languages
   '((latex . t) (emacs-lisp . t) (python . t) (shell . t) (css . t) (makefile . t)))
 '(org-capture-templates
   '(("p" "Project Todo" entry
      #'#[0 "\304\305\306\307\310\311\12!\312\313!\206\26\0r\312\314!q\210\13)\"\315\300\316\12\317\301&\11!\207"
            ["* TODO %?\12" nil org-project-capture-strategy default-directory occ-capture-edit-at-marker make-instance occ-context :category org-project-capture-category-from-file org-project-capture-strategy-get-backend org-capture-get :original-file
             :original-buffer :template :strategy :options]
            11]
      "* TODO %?\12")
     ("t" "Todo" entry (file+headline "refile.org" "Tasks To Refile") "* TODO %?\12:PROPERTIES:\12:DateCreated: %T\12:END:\12")
     ("n" "Quick note to refile later" entry (file+headline "refile.org" "Notes To Refile") "* %?\12        :PROPERTIES:\12        :DateCreated: %T\12        :END:\12%i\12%a")
     ("k" "keep" entry (file "keep.org") "* %? :crypt:\12        :PROPERTIES:\12        :DateCreated: %T\12        :END:\12%i\12%a")
     ("j" "journal" entry (file+olp+datetree "journal.org") "* %^{Title}\12        :PROPERTIES:\12        :DateCreated: %T\12        :END:" :empty-lines 1)
     ("o" "Orders" entry (file "~/.emacs.d/var/org/orgfiles/orders.org") "* WAITING %^{Order name} :order:\12SCHEDULED: %^{Delivery Date}t\12:PROPERTIES:\12:DateCreated: %T\12:END:")))
 '(org-catch-invisible-edits 'error nil nil "Customized with use-package org")
 '(org-clock-into-drawer t nil nil "Customized with use-package org")
 '(org-clock-persist 'history nil nil "Customized with use-package org")
 '(org-clock-sound "~/.emacs.d/ping.mp3")
 '(org-clock-task-overrun-text "*LATE*")
 '(org-columns-default-format "%80ITEM(Task) %10Effort(Effort){:} %10CLOCKSUM")
 '(org-confirm-babel-evaluate nil nil nil "Customized with use-package org")
 '(org-crypt-key "rileyrg")
 '(org-ctrl-k-protect-subtree t nil nil "Customized with use-package org")
 '(org-default-notes-file "refile.org" nil nil "Customized with use-package org")
 '(org-directory "/home/rgr/.emacs.d/var/org/orgfiles" nil nil "Customized with use-package org")
 '(org-enforce-todo-dependencies t nil nil "Customized with use-package org")
 '(org-fold-catch-invisible-edits 'error nil nil "Customized with use-package org")
 '(org-goto-interface 'outline-path-completion)
 '(org-goto-max-level 8)
 '(org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
 '(org-log-done 'time nil nil "Customized with use-package org")
 '(org-log-into-drawer t nil nil "Customized with use-package org")
 '(org-modules
   '(org-crypt ol-docview ol-eww ol-info ol-irc ol-mhe ol-rmail ol-w3m ol-eshell ol-bookmark ol-elisp-symbol ol-man))
 '(org-project-capture-projects-file "TODO.org")
 '(org-refile-allow-creating-parent-nodes 'confirm nil nil "Customized with use-package org")
 '(org-refile-targets
   '((org-agenda-files :tag . "refile") (org-agenda-files :maxlevel . 16)) nil nil "Customized with use-package org")
 '(org-return-follows-link t)
 '(org-reverse-note-order t nil nil "Customized with use-package org")
 '(org-src-window-setup 'current-window)
 '(org-structure-template-alist
   '(("py" . "src python") ("el" . "src emacs-lisp") ("sh" . "src shell") ("ba" . "src bash") ("a" . "export ascii") ("c" . "center") ("C" . "comment") ("e" . "example") ("E" . "export") ("h" . "export html") ("l" . "export latex") ("q" . "quote")
     ("s" . "src") ("v" . "verse")))
 '(org-tab-follows-link t)
 '(org-tag-alist
   '((:startgroup) (#("@caravan" 0 8 (face nil)) . 99) ("@shamrock" . 32) ("@home" . 104) ("@dublin" . 100) (:endgroup) (:startgroup) ("online" . 111) ("offline" . 79) (:endgroup) (:startgroup) ("personal" . 112) (:endgroup) ("electronics" . 69)
     ("emacs" . 101) ("fitness" . 102) ("gardening" . 103) ("toread" . 114) ("idea" . 97) ("programming" . 80) (#("shopping" 0 8 (face nil)) . 115) ("bill" . 98)))
 '(org-tag-persistent-alist '(("noexport" . 110) ("trash" . 116) ("refile" . 114)) nil nil "Customized with use-package org")
 '(org-tags-exclude-from-inheritance '("PROJECT" "DEFAULTCLOCKTASK" "crypt") nil nil "Customized with use-package org")
 '(org-todo-keywords
   '((sequence "TODO(t!)" "STARTED(s!)" "|" "DONE(d!/!)") (sequence "WAITING(w@/!)" "SOMEDAY(S!)" "OPEN(O@)" "|" "CANCELLED(c@/!)") (sequence "QUOTE(q!)" "QUOTED(Q!)" "|" "APPROVED(A@)" "EXPIRED(E@)" "REJECTED(R@)")))
 '(org-todo-state-tags-triggers
   '(("CANCELLED" ("CANCELLED" . t)) ("WAITING" ("WAITING" . t) ("NEXT")) ("SOMEDAY" ("WAITING" . t)) (done ("NEXT") ("WAITING")) ("TODO" ("WAITING") ("CANCELLED") ("NEXT")) ("STARTED" ("WAITING")) ("DONE" ("WAITING") ("CANCELLED") ("NEXT"))))
 '(org-use-property-inheritance t)
 '(persp-mode-prefix-key "\30P")
 '(php-manual-url "http://www.php.net")
 '(php-mode-speedbar-open nil)
 '(php-search-url "http://www.php.net/manual-lookup.php?pattern=")
 '(pomodoro-desktop-notification t)
 '(pos-tip-background-color "#FFFACE")
 '(pos-tip-foreground-color "#272822")
 '(ps-font-size '(12 . 12))
 '(ps-lpr-switches '("-o Duplex=DuplexNoTumble"))
 '(ps-paper-type 'a4)
 '(ps-spool-duplex t)
 '(python-indent-guess-indent-offset-verbose nil)
 '(rainbow-ansi-colors-major-mode-list '(sh-mode c-mode c++-mode php-mode emacs-lisp-mode))
 '(read-process-output-max 1048576 t)
 '(read-quoted-char-radix 16)
 '(rebox-style-loop '(27 25 21) t)
 '(recentf-max-saved-items 50)
 '(rgr/alert-learn-period 300)
 '(rgr/chat-close-functions '(slack-ws-close rgr/erc-quit))
 '(rgr/chat-functions '(rgr/erc-start))
 '(rgr/eww-external-launch-url-chunks '("youtube" "babeljs" "icons" "udemy" "i3wm" "execjs"))
 '(rgr/serialIOPort "/dev/ttyACM0")
 '(ring-bell-function 'ignore)
 '(safe-local-variable-values
   '((eval setq-local org-confirm-babel-evaluate nil) (eval progn (when (file-exists-p ".boilerplate") (setq boilerplate (with-temp-buffer (insert-file-contents ".boilerplate") (buffer-string))) (setq fname (buffer-file-name))))
     (eval dap-register-debug-template "cpptools::Run Configuration" (list :type "cppdbg" :request "launch" :name "cpptools::Run Configuration" :MIMode "gdb" :program "${workspaceFolder}/hello-world" :cwd "${workspaceFolder}"))
     (eval dap-register-debug-template "cpptools::Run Configuration" (list :type "cppdbg" :request "launch" :name "cpptools::Run Configuration" :MIMode "gdb" :target "${workspaceFolder}/hello-world" :cwd "${workspaceFolder}"))))
 '(save-abbrevs 'silently)
 '(save-interprogram-paste-before-kill t)
 '(scroll-bar-mode nil)
 '(scroll-conservatively 10000)
 '(scroll-step 1)
 '(search-default-mode t)
 '(send-mail-function 'smtpmail-send-it)
 '(set-mark-command-repeat-pop t)
 '(shell-switcher-ask-before-creating-new t)
 '(show-paren-delay 0.3)
 '(show-paren-mode t)
 '(show-paren-style 'parenthesis)
 '(shr-use-xwidgets-for-media t)
 '(smtpmail-smtp-server "smtp.gmail.com")
 '(sql-input-ring-file-name "~/.mysql_history")
 '(sql-port 5432)
 '(symfony-server-command "symfony serve")
 '(synonyms-cache-file "~/.emacs.d/syn.cache")
 '(synonyms-file "~/.emacs.d/mthesaur.txt")
 '(synosaurus-backend 'synosaurus-backend-openthesaurus)
 '(synosaurus-choose-method 'popup)
 '(tags-table-list nil)
 '(thesaurus-bhl-api-key "140ced1a60f9c434bb1dbc6831d2f6e9" t)
 '(treemacs-select-when-already-in-treemacs 'close)
 '(twittering-connection-type-order '(wget curl urllib-http native urllib-https))
 '(twittering-mode-hook nil)
 '(twittering-status-format
   "%RT{%FACE[bold]{RT}}%i %S(%s),  %@:\12%FOLD[  ]{%T // from %f%L%r%R%QT{\12+----\12%FOLD[|]{%i %s,  %@:\12%FOLD[  ]{%T // from %f%L%r%R}}\12+----}}\12 ")
 '(twittering-use-master-password t)
 '(uniquify-buffer-name-style 'forward nil (uniquify))
 '(url-standalone-mode nil)
 '(user-mail-address "rileyrg@gmx.de")
 '(vc-follow-symlinks t)
 '(version-control t)
 '(visible-bell t)
 '(vterm-always-compile-module t)
 '(warning-minimum-level :error)
 '(warning-suppress-log-types '((comp) (comp)))
 '(warning-suppress-types '((comp)))
 '(wg-session-file "~/.config/emacs/emacs_workgroups")
 '(whitespace-style '(tabs trailing lines-tail empty))
 '(windmove-wrap-around t)
 '(xref-prompt-for-identifier nil)
 '(yank-pop-change-selection t)
 '(zone-programs [zone-matrix] t))



(message "Custom loading completed.")
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:height 105))))
 '(compiler-explorer-cursor-entered ((t (:background "black" :foreground "orange red" :weight bold))))
 '(tab-bar ((t (:background "gray24" :foreground "#ffffff"))))
 '(tab-bar-tab ((t (:inherit bold :background "black" :foreground "#ffffff" :box (:line-width (2 . -2) :color "orange")))))
 '(tab-bar-tab-inactive ((t (:background "gray24" :foreground "#ffffff")))))
