(defun c-complete-line()
  (interactive)
  (end-of-line)
  (unless (eql ?\; (char-after (- (point-at-eol) 1)))
    (progn (insert ";")))
  (newline-and-indent))
(defun c-insert-previous-line()
  (interactive)
  (previous-line)
  (end-of-line)
  (newline-and-indent)
  (insert (string-trim (current-kill 0))))
(defun c-newline-below()
  (interactive)
  (end-of-line)
  (newline-and-indent))

(use-package scratch)

(provide 'rgr/utils)
