;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(#1=(#("mk.sh" 0 5
      (bmkp-full-record #1#))
    (filename . "~/bin/thirdparty/llvm-project/mk.sh")
    (front-context-string)
    (rear-context-string . "NABLE_PYTHON=1 \n")
    (position . 168))
#1=(#("(emacs) Top" 0 11
      (bmkp-full-record #1#))
    (front-context-string . "\nThe Emacs Edito")
    (rear-context-string . "rib,  Up: (dir)\n")
    (position . 1141)
    (filename . "/home/rgr/development/projects/emacs/emacs/info/emacs")
    (info-node . "Top")
    (handler . Info-bookmark-jump))
#1=(#("udemy" 0 5
      (bmkp-full-record #1#))
    (filename . "~/development/education/Udemy/UdemyCpp/1_CppGrundlagen/Main.cc")
    (front-context-string . "          i++;\n ")
    (rear-context-string . "<10;i++)\n     {\n")
    (position . 1471))
#1=(#("extensions" 0 10
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/var/dap/extensions/")
    (front-context-string)
    (rear-context-string . " Jun  9 14:08   ")
    (position . 223))
#1=(#(".vscode" 0 7
      (bmkp-full-record #1#))
    (filename . "~/.vscode/")
    (front-context-string)
    (rear-context-string . " 8. Jun 20:37   ")
    (position . 236))
#1=(#("UdemyCpp" 0 8
      (bmkp-full-record #1#))
    (filename . "~/development/education/Udemy/UdemyCpp/")
    (front-context-string . "10_LambdaFunktio")
    (rear-context-string . "6  7. Jun 15:51 ")
    (position . 204))
#1=(#("(emacs) Tab Bars" 0 16
      (bmkp-full-record #1#))
    (front-context-string . "\n21.17 Tab Bars\n")
    (rear-context-string . "rs,  Up: Frames\n")
    (position . 673142)
    (filename . "/home/rgr/development/projects/emacs/emacs/info/emacs")
    (info-node . "Tab Bars")
    (handler . Info-bookmark-jump))
#1=(#("swaymsg - Send messages to a running instance of sway over the IPC" 0 66
      (bmkp-full-record #1#))
    (front-context-string . "swaymsg(1)      ")
    (rear-context-string)
    (position . 1)
    (location .
              #("man 1 swaymsg" 6 13
                (help-echo #2="Send messages to a running instance of sway over the IPC socket.")))
    (man-args .
              #("1 swaymsg" 2 9
                (help-echo #2#)))
    (handler . Man-bookmark-jump))
#1=(#("steamapps" 0 9
      (bmkp-full-record #1#))
    (filename . "~/.steam/steam/steamapps/")
    (front-context-string . "appmanifest_1113")
    (rear-context-string . "96 May 11 11:07 ")
    (position . 218))
#1=(#("jq - Command-line JSON processor" 0 32
      (bmkp-full-record #1#))
    (front-context-string . "SYNOPSIS\n       ")
    (rear-context-string . "JSON processor\n\n")
    (position . 127)
    (location . "man -a jq")
    (man-args . "-a jq")
    (handler . Man-bookmark-jump))
#1=(#("sway" 0 4
      (bmkp-full-record #1#))
    (filename . "~/.config/sway/")
    (front-context-string)
    (rear-context-string . "38 May 18 14:01 ")
    (position . 210))
#1=(#("systemd" 0 7
      (bmkp-full-record #1#))
    (filename . "~/.config/systemd/")
    (front-context-string)
    (rear-context-string . "96 May 13 10:13 ")
    (position . 210))
#1=(#(".config" 0 7
      (bmkp-full-record #1#))
    (filename . "~/.config/")
    (front-context-string . "autostart\n  lrwx")
    (rear-context-string . "96 May  6 13:59 ")
    (position . 203))
#1=(#("(elisp) Defining Minor Modes" 0 28
      (bmkp-full-record #1#))
    (front-context-string . "\n24.3.3 Defining")
    (rear-context-string . "Up: Minor Modes\n")
    (position . 1498260)
    (filename . "/home/rgr/development/projects/emacs/emacs/info/elisp")
    (info-node . "Defining Minor Modes")
    (handler . Info-bookmark-jump))
#1=(#("(elisp) Minor Modes" 0 19
      (bmkp-full-record #1#))
    (front-context-string . "\n24.3 Minor Mode")
    (rear-context-string . "des,  Up: Modes\n")
    (position . 1489898)
    (filename . "/home/rgr/development/projects/emacs/emacs/info/elisp")
    (info-node . "Minor Modes")
    (handler . Info-bookmark-jump))
#1=(#("lazy-lang-learn.el" 0 18
      (bmkp-full-record #1#))
    (filename . "~/development/projects/emacs/lazy-lang-learn/lazy-lang-learn.el")
    (front-context-string . "      (unless la")
    (rear-context-string . "ang-learn-mode)\n")
    (position . 2859))
#1=(#("lll" 0 3
      (bmkp-full-record #1#))
    (filename . "~/development/projects/emacs/lazy-lang-learn/lazy-lang-learn.el")
    (front-context-string . "      (unless la")
    (rear-context-string . "ang-learn-mode)\n")
    (position . 2859))
#1=(#("lazy-lang-learn" 0 15
      (bmkp-full-record #1#))
    (filename . "~/development/projects/emacs/lazy-lang-learn/")
    (front-context-string . "lazy-lang-learn.")
    (rear-context-string . "59 May 12 00:37 ")
    (position . 337))
#1=(#(".steam" 0 6
      (bmkp-full-record #1#))
    (filename . "~/.steam/")
    (front-context-string . "bin -> /home/rgr")
    (rear-context-string . "22 May 11 22:46 ")
    (position . 201))
#1=(#(".local" 0 6
      (bmkp-full-record #1#))
    (filename . "~/.local/")
    (front-context-string)
    (rear-context-string . "96 May 11 14:10 ")
    (position . 201))
#1=(#("native" 0 6
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/eln-cache/")
    (front-context-string . "28.0.50-33806cd2")
    (rear-context-string . "12 May 11 15:02 ")
    (position . 217))
#1=(#("eln-cache" 0 9
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/eln-cache/")
    (front-context-string . "28.0.50-33806cd2")
    (rear-context-string . "12 May 11 15:02 ")
    (position . 217))
#1=(#("init.el" 0 7
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/init.el")
    (front-context-string . "sp\" no-littering")
    (rear-context-string . "d-file-name \"eli")
    (position . 1204))
#1=(#("(elisp) Composite Types" 0 23
      (bmkp-full-record #1#))
    (front-context-string . "     the choices")
    (rear-context-string . "omatically from\n")
    (position . 789738)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Composite Types")
    (handler . Info-bookmark-jump))
#1=(#("(elisp) Quoting" 0 15
      (bmkp-full-record #1#))
    (front-context-string . "\n10.3 Quoting\n==")
    (rear-context-string . " Up: Evaluation\n")
    (position . 443948)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Quoting")
    (handler . Info-bookmark-jump))
#1=(#("(elisp) Top" 0 11
      (bmkp-full-record #1#))
    (front-context-string . "\nEmacs Lisp\n****")
    (rear-context-string . "ion,  Up: (dir)\n")
    (position . 1110)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Top")
    (handler . Info-bookmark-jump))
#1=(#("build" 0 5
      (bmkp-full-record #1#))
    (time 25812 1539 910517 520000)
    (visits . 0)
    (filename . "~/.emacs.d/var/straight/build/")
    (front-context-string . "ace-jump-mode\n  ")
    (rear-context-string . "6 23. Apr 23:14 ")
    (position . 252))
#1=(#("el-docstring-sap" 0 16
      (bmkp-full-record #1#))
    (filename . "~/development/projects/emacs/el-docstring-sap/")
    (front-context-string . "el-docstring-at-")
    (rear-context-string . "21. Apr 13:28   ")
    (position . 245))
#1=(#("el-docstring-sap.el" 0 19
      (bmkp-full-record #1#))
    (filename . "~/development/projects/emacs/el-docstring-sap/el-docstring-sap.el")
    (front-context-string . "'.\"\n  (interacti")
    (rear-context-string . "`symbol-at-point")
    (position . 5292))
#1=(#("(elisp) Property Lists" 0 22
      (bmkp-full-record #1#))
    (front-context-string . "A “property list")
    (rear-context-string . "==============\n\n")
    (position . 330353)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Property Lists")
    (handler . Info-bookmark-jump))
#1=(#("plist" 0 5
      (bmkp-full-record #1#))
    (front-context-string . "A “property list")
    (rear-context-string . "==============\n\n")
    (position . 330353)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Property Lists")
    (handler . Info-bookmark-jump))
#1=(#("scratch.el" 0 10
      (bmkp-full-record #1#))
    (filename . "~/tmp/scratch.el")
    (front-context-string)
    (rear-context-string)
    (position . 1))
#1=(#("org-capture-last-stored-marker" 0 30
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/var/org/orgfiles/linux.org")
    (front-context-string . "** install calf ")
    (rear-context-string . "-tools\n\n* Music\n")
    (position . 30757))
#1=(#("treemacs" 0 8
      (bmkp-full-record #1#))
    (filename . "~/development/projects/emacs/treemacs/src/")
    (front-context-string . "treemacs-async.e")
    (rear-context-string . "19. Mär 19:24   ")
    (position . 243))
#1=(#("treemacs.el" 0 11
      (bmkp-full-record #1#))
    (filename . "~/development/projects/emacs/treemacs/src/elisp/treemacs.el")
    (front-context-string . "(defun treemacs ")
    (rear-context-string . "\n;;;###autoload\n")
    (position . 2306))
#1=(#("ctrlf.el" 0 8
      (bmkp-full-record #1#))
    (filename . "~/development/projects/emacs/ctrlf/ctrlf.el")
    (front-context-string . "(defun ctrlf-for")
    (rear-context-string . "\n;;;###autoload\n")
    (position . 50183))
#1=(#("ook" 0 3
      (bmkp-full-record #1#))
    (filename . "/home/rgr/development/projects/emacs/centaur-tabs/images"))
(""
 (filename . "/home/rgr/development/projects/emacs/centaur-tabs/images"))
#1=(#("cent" 0 4
      (bmkp-full-record #1#))
    (filename . "/home/rgr/development/projects/emacs/centaur-tabs/README.org"))
#1=(#("snippets" 0 8
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/etc/straight/build/yasnippet-snippets/snippets/")
    (front-context-string . "antlr-mode\n  drw")
    (rear-context-string . " 7. Apr 23:38   ")
    (position . 226))
#1=(#("(forge) Branching" 0 17
      (bmkp-full-record #1#))
    (front-context-string . "\n4.2 Branching\n=")
    (rear-context-string . "ing,  Up: Usage\n")
    (position . 18899)
    (filename . "/home/rgr/.emacs.d/etc/straight/build/forge/forge")
    (info-node . "Branching")
    (handler . Info-bookmark-jump))
#1=(#("lsp-python-ms.el" 0 16
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/etc/straight/repos/lsp-python-ms/lsp-python-ms.el")
    (front-context-string . ";;; lsp-python-m")
    (rear-context-string)
    (position . 1))
#1=(#("lsp-python-ms" 0 13
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/etc/straight/repos/lsp-python-ms/")
    (front-context-string . "Cask\n  drwxr-xr-")
    (rear-context-string . "6 15. Mär 01:44 ")
    (position . 212))
#1=(#("lsp-python-ms.el*" 0 17
      (bmkp-full-record #1#))
    (filename . "~/development/projects/emacs/lsp-python-ms/lsp-python-ms.el*")
    (front-context-string . "lsp-python-ms.el")
    (rear-context-string . " 5. Apr 16:55   ")
    (position . 129))
#1=(#("(elisp) Interactive Call" 0 24
      (bmkp-full-record #1#))
    (front-context-string . "\n21.3 Interactiv")
    (rear-context-string . "p: Command Loop\n")
    (position . 1159378)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Interactive Call")
    (handler . Info-bookmark-jump))
#1=(#("hellopackage" 0 12
      (bmkp-full-record #1#))
    (filename . "~/development/education/lessons/python/helloworld/hellopackage/")
    (front-context-string . "..\n  -rw-r--r-- ")
    (rear-context-string . " 4. Apr 10:37   ")
    (position . 180))
#1=(#("helloworld" 0 10
      (bmkp-full-record #1#))
    (filename . "~/development/education/lessons/python/helloworld/")
    (front-context-string . "main.py\n  drwxr-")
    (rear-context-string . " 3. Apr 22:27   ")
    (position . 330))
#1=(#("main" 0 4
      (bmkp-full-record #1#))
    (filename . "~/development/education/lessons/python/helloworld/main.py")
    (front-context-string)
    (rear-context-string . "Pussy(\"stella\")\n")
    (position . 443))
#1=(#("Fluent Python.pdf" 0 17
      (bmkp-full-record #1#))
    (filename . "~/Documents/Programming/Python/Fluent Python.pdf")
    (position . 1)
    (page . 32)
    (slice)
    (size . 1.9301587301587302)
    (origin 0.0 . 0.0)
    (handler . pdf-view-bookmark-jump-handler))
#1=(#("dog.py" 0 6
      (bmkp-full-record #1#))
    (filename . "~/development/education/lessons/python/helloworld/hellopackage/dog.py")
    (front-context-string . "Pussy(Dog):\n    ")
    (rear-context-string . "ge))\n\n\nclass Dog")
    (position . 556))
#1=(#("19-slicing.org" 0 14
      (bmkp-full-record #1#))
    (filename . "~/development/education/lessons/python/coreyschafer/19-slicing.org")
    (front-context-string)
    (rear-context-string . ", 5, 6, 7, 8.9]\n")
    (position . 1402))
#1=(#("comprehensions.org" 0 18
      (bmkp-full-record #1#))
    (filename . "~/development/education/lessons/python/comprehensions.org")
    (front-context-string . "#+PROPERTY: head")
    (rear-context-string)
    (position . 1))
#1=(#("python-lessons" 0 14
      (bmkp-full-record #1#))
    (filename . "~/development/education/lessons/python/")
    (front-context-string . "comprehensions.o")
    (rear-context-string . "6 26. Mär 23:47 ")
    (position . 197))
#1=(#("list-comprehensions.py" 0 22
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/var/lessons/python-lessons/comprehensions/")
    (front-context-string . "\nmyl = [(l, n) f")
    (rear-context-string . "print(myl)\n\n# lc")
    (position . 877))
#1=(#("emacs.org" 0 9
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/var/org/orgfiles/emacs.org")
    (front-context-string . "#+TITLE: Emacs\n#")
    (rear-context-string)
    (position . 1))
#1=(#("python-lernen.de" 0 16
      (bmkp-full-record #1#))
    (filename . "~/development/projects/Python/python-lernen.de/")
    (front-context-string)
    (rear-context-string . "5. Mär 08:46 ..\n")
    (position . 162))
#1=(#("Python" 0 6
      (bmkp-full-record #1#))
    (filename . "~/development/projects/Python/")
    (front-context-string)
    (rear-context-string . "6 15. Mär 00:54 ")
    (position . 188))
#1=(#("terminator config" 0 17
      (bmkp-full-record #1#))
    (filename . "~/.config/terminator/config")
    (front-context-string . "[global_config]\n")
    (rear-context-string)
    (position . 1))
#1=(#("org agenda files list" 0 21
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/etc/org/agenda-files.txt")
    (front-context-string . "~/.emacs.d/var/o")
    (rear-context-string)
    (position . 1))
#1=(#("ob-tangle.el" 0 12
      (bmkp-full-record #1#))
    (filename . "~/~/emacs.d/etc/straight/repos/org/lisp/ob-tangle.el")
    (front-context-string . "(defun org-babel")
    (rear-context-string . "\n;;;###autoload\n")
    (position . 7412))
#1=(#("inttobin.c" 0 10
      (bmkp-full-record #1#))
    (filename . "~/development/projects/C/inttobin/inttobin.c")
    (front-context-string . "\n	unsigned int b")
    (rear-context-string . " num, char *p)\n{")
    (position . 154))
#1=(#("inttobin" 0 8
      (bmkp-full-record #1#))
    (filename . "~/development/projects/C/inttobin/")
    (front-context-string . "inttobin.c\n  -rw")
    (rear-context-string . "5 20. Nov 19:43 ")
    (position . 781))
#1=(#("C" 0 1
      (bmkp-full-record #1#))
    (filename . "~/development/projects/C/")
    (front-context-string . "inttobin\n  drwxr")
    (rear-context-string . "6 26. Feb 10:18 ")
    (position . 298))
#1=(#("projects" 0 8
      (bmkp-full-record #1#))
    (filename . "~/development/projects/")
    (front-context-string . "C\n  drwxr-xr-x 1")
    (rear-context-string . "6 24. Nov 11:28 ")
    (position . 235))
#1=(#("(emacs) Regexps" 0 15
      (bmkp-full-record #1#))
    (front-context-string . "\n15.6 Syntax of ")
    (rear-context-string . "ch,  Up: Search\n")
    (position . 359588)
    (filename . "/usr/share/info/emacs/emacs")
    (info-node . "Regexps")
    (handler . Info-bookmark-jump))
#1=(#("orgfiles" 0 8
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/var/org/orgfiles/")
    (front-context-string . "ardour.org\n  -rw")
    (rear-context-string . "35 Dec 29 16:56 ")
    (position . 226))
#1=(#("(org) Global and local cycling" 0 30
      (bmkp-full-record #1#))
    (front-context-string . "\n2.3.1 Global an")
    (rear-context-string . "ibility cycling\n")
    (position . 41218)
    (filename . "/usr/share/info/emacs/org")
    (info-node . "Global and local cycling")
    (handler . Info-bookmark-jump))
#1=(#("(org) Visibility cycling" 0 24
      (bmkp-full-record #1#))
    (front-context-string . "\n* Global and lo")
    (rear-context-string . "======\n\n* Menu:\n")
    (position . 40890)
    (filename . "/usr/share/info/emacs/org")
    (info-node . "Visibility cycling")
    (handler . Info-bookmark-jump))
#1=(#("org motion movement" 0 19
      (bmkp-full-record #1#))
    (front-context-string . "\nThe following c")
    (rear-context-string . "tion\n==========\n")
    (position . 45861)
    (filename . "/usr/share/info/emacs/org")
    (info-node . "Motion")
    (handler . Info-bookmark-jump))
#1=(#("swap-workspace.py" 0 17
      (bmkp-full-record #1#))
    (filename . "~/tmp/swap-workspace.py")
    (front-context-string . "#!/usr/bin/pytho")
    (rear-context-string)
    (position . 1))
#1=(#("tmp" 0 3
      (bmkp-full-record #1#))
    (filename . "~/tmp/")
    (front-context-string . "158c9c7b25afac14")
    (rear-context-string . "2 16. Feb 14:04 ")
    (position . 178))
#1=(#("dap mode task" 0 13
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/var/org/orgfiles/emacs.org")
    (front-context-string . "at dap-mode opti")
    (rear-context-string . "TODO 10:12 look ")
    (position . 4482))
#1=(#("llvm-project" 0 12
      (bmkp-full-record #1#))
    (filename . "~/bin/thirdparty/llvm-project/")
    (front-context-string . ".arcconfig\n  -rw")
    (rear-context-string . " Jun 30 14:24   ")
    (position . 229))
#1=(#(".git" 0 4
      (bmkp-full-record #1#))
    (filename . "~/bin/thirdparty/llvm-project/.git/")
    (front-context-string . "branches\n  -rw-r")
    (rear-context-string . "18. Feb 17:09   ")
    (position . 217))
#1=(#("thirdparty" 0 10
      (bmkp-full-record #1#))
    (filename . "~/bin/thirdparty/")
    (front-context-string . "acpilight\n  lrwx")
    (rear-context-string . "6 20. Dez 15:06 ")
    (position . 182))
#1=(#("xresources" 0 10
      (bmkp-full-record #1#))
    (filename . "~/Dropbox/homefiles/linux-config.org")
    (front-context-string . "ources\n   #+begi")
    (rear-context-string . "d_src\n** ~/.Xres")
    (position . 6635))
#1=(#("smart-connect" 0 13
      (bmkp-full-record #1#))
    (filename . "~/Dropbox/homefiles/linux-config.org")
    (front-context-string . "tangle ~/bin/xra")
    (rear-context-string . "begin_src bash :")
    (position . 13983))
#1=(#("10-nvidia-drm-outputclass.conf" 0 30
      (bmkp-full-record #1#))
    (filename . "/sudo:root@localhost:/etc/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf")
    (front-context-string)
    (rear-context-string . "les\"\n#EndSection")
    (position . 377))
#1=(#("journals" 0 8
      (bmkp-full-record #1#))
    (filename . "~/~/emacs.d/var/org/orgfiles/journals/")
    (front-context-string . "20200209.org\n  -")
    (rear-context-string . "77 Feb 28  2020 ")
    (position . 256))
#1=(#("lessons" 0 7
      (bmkp-full-record #1#))
    (filename . "~/development/education/lessons/")
    (front-context-string . "advice.org\n  drw")
    (rear-context-string . "8 25. Jan 19:35 ")
    (position . 193))
#1=(#(".Xresources" 0 11
      (bmkp-full-record #1#))
    (filename . "~/Dropbox/homefiles/DotFiles/.Xresources")
    (front-context-string . "urxvt.font: xft:")
    (rear-context-string)
    (position . 1))
#1=(#("Music" 0 5
      (bmkp-full-record #1#))
    (filename . "~/Music/")
    (front-context-string . "05 Robin Thicke ")
    (rear-context-string . "13 Aug 31  2014 ")
    (position . 223))
#1=(#("(cl) Structures" 0 15
      (bmkp-full-record #1#))
    (front-context-string . "or lists upon re")
    (rear-context-string . "res as vectors (")
    (position . 153727)
    (filename . "/usr/share/info/emacs/cl")
    (info-node . "Structures")
    (handler . Info-bookmark-jump))
#1=(#("Dropbox" 0 7
      (bmkp-full-record #1#))
    (filename . "~/Dropbox/")
    (front-context-string . "homefiles\n  drwx")
    (rear-context-string . "96 Jan 25 14:56 ")
    (position . 477))
#1=(#("(elisp) Edebug" 0 14
      (bmkp-full-record #1#))
    (front-context-string . "\n18.2 Edebug\n===")
    (rear-context-string . "  Up: Debugging\n")
    (position . 890027)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Edebug")
    (handler . Info-bookmark-jump))
#1=(#("vollfilm-new" 0 12
      (bmkp-full-record #1#))
    (filename . "~/development/projects/vollfilm-new/")
    (front-context-string . "apache2\n  drwxr-")
    (rear-context-string . "96 Dec 28 21:21 ")
    (position . 238))
#1=(#("development" 0 11
      (bmkp-full-record #1#))
    (filename . "~/development/")
    (front-context-string . "arduino\n  drwxr-")
    (rear-context-string . "96 Dec 28 21:20 ")
    (position . 206))
#1=(#("ctrlf" 0 5
      (bmkp-full-record #1#))
    (filename . "~/development/projects/emacs/ctrlf/")
    (front-context-string . "CHANGELOG.md\n  d")
    (rear-context-string . " 9. Apr 22:40   ")
    (position . 233))
#1=(#("mu*" 0 3
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/etc/straight/repos/mu/mu/mu*")
    (front-context-string . "mu\n  -rw-r--r-- ")
    (rear-context-string . "28 Jan 14 18:12 ")
    (position . 107))
#1=(#("mu" 0 2
      (bmkp-full-record #1#))
    (filename . "~/bin/thirdparty/mu/")
    (front-context-string . "README.org\n  -rw")
    (rear-context-string . "39 Jan  7 15:23 ")
    (position . 2253))
#1=(#("emacs-config" 0 12
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/emacs-config.org")
    (front-context-string . "[[https://github")
    (rear-context-string . "3b\n   :END:\n*** ")
    (position . 2147))
#1=(#("debus-services" 0 14
      (bmkp-full-record #1#))
    (filename . "/usr/share/dbus-1/services/")
    (front-context-string . "ca.desrt.dconf-e")
    (rear-context-string . "93 Sep 15 20:42 ")
    (position . 216))
#1=(#("etc-hosts" 0 9
      (bmkp-full-record #1#))
    (filename . "/etc/hosts")
    (front-context-string . "\nff02::2 ip6-all")
    (rear-context-string . "::1 ip6-allnodes")
    (position . 222))
#1=(#("etc" 0 3
      (bmkp-full-record #1#))
    (filename . "/etc/")
    (front-context-string . "acpi\n  -rw-r--r-")
    (rear-context-string . "6 27. Dez 23:37 ")
    (position . 181))
#1=(#("hosts" 0 5
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/etc/hosts/")
    (front-context-string . "..\n  drwxr-xr-x ")
    (rear-context-string . "6 11. Jan 10:20 ")
    (position . 145))
#1=(#("custom" 0 6
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/custom.el")
    (front-context-string . "(custom-set-vari")
    (rear-context-string)
    (position . 1))
#1=(#("linux-config" 0 12
      (bmkp-full-record #1#))
    (filename . "~/Dropbox/homefiles/linux-config.org")
    (front-context-string . "d\n**  ~/.profile")
    (rear-context-string . "]\n\n* Bash relate")
    (position . 19971))
#1=(#("init.org" 0 8
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/init.org")
    (front-context-string . "[[https://github")
    (rear-context-string . "3b\n   :END:\n*** ")
    (position . 2620))
#1=(#("emacs-var" 0 9
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/var/")
    (front-context-string . "auto-save\n  drwx")
    (rear-context-string . "6 11. Jan 00:42 ")
    (position . 196))
#1=(#("emacs-etc" 0 9
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/etc/")
    (front-context-string . "elisp\n  drwxr-xr")
    (rear-context-string . "6 11. Jan 10:20 ")
    (position . 342))
#1=(#("test" 0 4
      (bmkp-full-record #1#))
    (position . 69)
    (help-fn . describe-variable)
    (help-args bookmark-file "*Help*")
    (position . 69)
    (handler . help-bookmark-jump))
#1=(#("home" 0 4
      (bmkp-full-record #1#))
    (filename . "~/")
    (front-context-string . "Dropbox\n  drwxrw")
    (rear-context-string . "6 12. Jan 23:39 ")
    (position . 2783))
#1=(#("i3-config" 0 9
      (bmkp-full-record #1#))
    (filename . "~/Dropbox/homefiles/linux-config.org")
    (front-context-string . "     # Maintaine")
    (rear-context-string . "onfig/i3/config\n")
    (position . 34588))
#1=(#("i3blocks" 0 8
      (bmkp-full-record #1#))
    (filename . "~/Dropbox/homefiles/linux-init-files.org")
    (front-context-string . "s\n*** ~/bin/my-b")
    (rear-context-string . " such as i3block")
    (position . 73761))
#1=(#("org-capture-last-stored" 0 23
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/var/org/orgfiles/refile.org")
    (front-context-string . "** TODO really n")
    (rear-context-string . "Tasks To Refile\n")
    (position . 92))
#1=(#("common" 0 6
      (bmkp-full-record #1#))
    (filename . "~/SteamGames/steamapps/common/")
    (front-context-string . "Assassin's Creed")
    (rear-context-string . "96 Jan  5 12:31 ")
    (position . 222))
#1=(#("home<2>" 0 7
      (bmkp-full-record #1#))
    (filename . "~/")
    (front-context-string . ".xmonad -> /home")
    (rear-context-string . "44 Dec 18 23:50 ")
    (position . 12661))
#1=(#("cur" 0 3
      (bmkp-full-record #1#))
    (filename . "~/SteamGames/steamapps/common/Assassin's Creed IV Black Flag/")
    (front-context-string . "DataPC_TitleScre")
    (rear-context-string . "72 Jan  5 12:30 ")
    (position . 2408))
#1=(#("xidlehook" 0 9
      (bmkp-full-record #1#))
    (filename . "~/Dropbox/homefiles/linux-init-files.org")
    (front-context-string . "      xidlehook ")
    (rear-context-string . "v/null || true\n\n")
    (position . 9070))
#1=(#("Xsession.d" 0 10
      (bmkp-full-record #1#))
    (filename . "/etc/X11/Xsession.d/")
    (front-context-string . ":\n  insgesamt 80")
    (rear-context-string . "c/X11/Xsession.d")
    (position . 22))
#1=(#("auth" 0 4
      (bmkp-full-record #1#))
    (filename . "~/.gnupg/auth/")
    (front-context-string . "authmbsync.gpg\n ")
    (rear-context-string . "4  7. Jan 05:24 ")
    (position . 344))
#1=(#(".gnupg" 0 6
      (bmkp-full-record #1#))
    (filename . "~/.gnupg/")
    (front-context-string . "auth\n  drwx-----")
    (rear-context-string . "6  7. Jan 05:20 ")
    (position . 174))
#1=(#("Mail" 0 4
      (bmkp-full-record #1#))
    (filename . "~/Maildir/")
    (front-context-string . "Bookings\n  drwx-")
    (rear-context-string . "6  7. Jan 05:38 ")
    (position . 171))
#1=(#(".xsessionrc.local" 0 17
      (bmkp-full-record #1#))
    (filename . "~/.xsessionrc.local")
    (front-context-string)
    (rear-context-string)
    (position . 13))
#1=(#("bin" 0 3
      (bmkp-full-record #1#))
    (filename . "~/bin/")
    (front-context-string . "acpi-powerstate-")
    (rear-context-string . "64 Dec 27 13:40 ")
    (position . 202))
#1=(#("org-refile-last-stored" 0 22
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/emacs-config.org")
    (front-context-string . "****** TODO real")
    (rear-context-string . "))\n\n  #+end_src\n")
    (position . 97915))
#1=(#("x11-xsession" 0 12
      (bmkp-full-record #1#))
    (filename . "/etc/X11/Xsession")
    (front-context-string . "\nUSERXSESSION=$H")
    (rear-context-string . "c/X11/Xsession.d")
    (position . 1643))
#1=(#("custom.el" 0 9
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/custom.el")
    (front-context-string . "(custom-set-vari")
    (rear-context-string)
    (position . 1))
#1=(#("thinkpadx270" 0 12
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/elisp/hosts/thinkpadx270/")
    (front-context-string)
    (rear-context-string . "1 30. Dez 19:43 ")
    (position . 194))
#1=(#("elisp" 0 5
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/etc/elisp/")
    (front-context-string . "rgr-alert-learn.")
    (rear-context-string . "7 22. Apr 12:38 ")
    (position . 182))
#1=(#("repos" 0 5
      (bmkp-full-record #1#))
    (end-position . 456)
    (time 25812 1554 489620 941000)
    (visits . 0)
    (filename . "~/.emacs.d/straight/repos/ace-link/")
    (front-context-string . "mu4e\n  drwxr-xr-")
    (rear-context-string . "96 Jan 14 16:39 ")
    (position . 456))
#1=(#("straight" 0 8
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/etc/straight/repos/")
    (front-context-string . "build\n  -rw-r--r")
    (rear-context-string . "76 Dec 29 23:25 ")
    (position . 227))
#1=(#("emacs" 0 5
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/")
    (front-context-string . "etc\n  drwxr-xr-x")
    (rear-context-string . "6 29. Apr 11:56 ")
    (position . 587))

)
