;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(#1=(#("emacs-condif-delme" 0 18
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/emacs-config.org")
    (buffer-name . "emacs-config.org")
    (front-context-string . "#+TITLE: Emacs c")
    (rear-context-string)
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 0)
    (time . #2=(24823 52712 384968 103000))
    (created . #2#)
    (position . 1))
#1=(#("info" 0 4
      (bmkp-full-record #1#))
    (buffer-name . "*info*")
    (front-context-string . "\n  This (the Dir")
    (rear-context-string . "f the INFO tree\n")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 0)
    (time . #2=(24823 51269 36387 158000))
    (created . #2#)
    (position . 227)
    (filename . "dir")
    (info-node . #3="Top")
    (handler . Info-bookmark-jump)
    (defaults "(dir) Top" "dir" #3#))
#1=(#("org-refile-last-stored" 0 22
      (bmkp-full-record #1#))
    (annotation)
    (tags)
    (filename . "~/.emacs.d/var/org/orgfiles/diy.org")
    (buffer-name . "diy.org")
    (front-context-string . "** DONE [#A] tru")
    (rear-context-string . "tors\n\n* caravan\n")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 0)
    (time . #2=(24815 33451 566209 507000))
    (created . #2#)
    (position . 2237))
#1=(#("main.cc" 0 7
      (bmkp-full-record #1#))
    (filename . "~/development/education/Udemy/UdemyCpp/Computerspiel1/main.cc")
    (buffer-name . "main.cc")
    (front-context-string . "\n     while (rep")
    (rear-context-string . "= *pms;\n     ms.")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 1)
    (time 24823 51937 48939 132000)
    (created 24806 4721 88196 464000)
    (position . 546))
#1=(#("squid.conf" 0 10
      (bmkp-full-record #1#))
    (end-position . 69685)
    (filename . "/sudo:root@localhost:/etc/squid/squid.conf")
    (buffer-name . "squid.conf")
    (front-context-string . "\n\n#  TAG: https_")
    (rear-context-string . "8\nhttp_port 3128")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 2)
    (time 24823 51938 721116 312000)
    (created 24803 29360 549722 460000)
    (position . 69685))
#1=(#("emacs-config.org" 0 16
      (bmkp-full-record #1#))
    (end-position . 1)
    (time 24823 52508 184044 452000)
    (visits . 8)
    (tags
     #("config" 0 6
       (face nil))
     #("current" 0 7
       (face nil)))
    (filename . "/home/rgr/.emacs.d/emacs-config.org")
    (position . 1)
    (created 24802 49421 451802 453000))
#1=(#("Makefile" 0 8
      (bmkp-full-record #1#))
    (tags "makefile")
    (filename . "/home/rgr/Dropbox/homefiles/directories/development/education/Udemy/UdemyCpp/.vscode/Makefile")
    (position . 0)
    (created 24802 47091 438620 950000))
#1=(#("CLANGD(1)" 0 9
      (bmkp-full-record #1#))
    (buffer-name . "*Man 1 clangd*")
    (front-context-string . "CLANGD(1)       ")
    (rear-context-string)
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 0)
    (time . #2=(24802 14287 263536 350000))
    (created . #2#)
    (position . 1)
    (location . "man 1 clangd")
    (man-args . "1 clangd")
    (handler . Man-bookmark-jump))
#1=(#("LLVM Tutorial: Table of Contents — LLVM 13 documentation" 0 56
      (bmkp-full-record #1#))
    (annotation)
    (tags "lldb" "current" "llvm")
    (buffer-name . "*eww*")
    (buffer-name . "*eww*")
    (front-context-string . "\n2.1. Chapter 2 ")
    (rear-context-string . "ll Code Listing\n")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 11)
    (time 24803 29616 337532 947000)
    (created 24802 44874 25117 897000)
    (position . 734)
    (location . "https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/LangImpl02.html#chapter-2-introduction")
    (handler . bmkp-jump-eww))
#1=(#("build" 0 5
      (bmkp-full-record #1#))
    (buffer-name . "build")
    (front-context-string . "eshell-git-promp")
    (rear-context-string . " Jun 24 08:17   ")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 0)
    (time . #2=(24802 9905 396855 720000))
    (created . #2#)
    (position . 4109)
    (filename . "/home/rgr/.emacs.d/straight/build/")
    (dired-directory . "~/.emacs.d/straight/build/")
    (dired-marked)
    (dired-switches . "-al")
    (dired-subdirs)
    (dired-hidden-dirs)
    (handler . bmkp-jump-dired))
#1=(#("repos" 0 5
      (bmkp-full-record #1#))
    (tags "straight")
    (buffer-name . "repos")
    (front-context-string . "bookmark-plus\n  ")
    (rear-context-string . " Jun 30 16:15   ")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 2)
    (time 24823 51952 125919 278000)
    (created 24802 9898 460908 62000)
    (position . 1351)
    (filename . "/home/rgr/.emacs.d/straight/repos/")
    (dired-directory . "~/.emacs.d/straight/repos/")
    (dired-marked)
    (dired-switches . "-al")
    (dired-subdirs)
    (dired-hidden-dirs)
    (handler . bmkp-jump-dired))
#1=(#("org-capture-last-stored" 0 23
      (bmkp-full-record #1#))
    (annotation)
    (tags)
    (filename . "~/.emacs.d/var/org/orgfiles/journal.org")
    (buffer-name . "journal.org")
    (front-context-string . "**** dired-filte")
    (rear-context-string . "-07-20 Tuesday\n\n")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 0)
    (time . #2=(24822 19708 688044 956000))
    (created . #2#)
    (position . 20767))
#1=(#("1_CppGrundlagen" 0 15
      (bmkp-full-record #1#))
    (end-position . 1)
    (time 24802 9653 442127 847000)
    (visits . 0)
    (tags "udemy")
    (filename . "/home/rgr/development/education/Udemy/UdemyCpp/1_CppGrundlagen/")
    (position . 1)
    (created 24798 49404 382047 270000))
#1=(#("Building LLVM with CMake — LLVM 13 documentation" 0 48
      (bmkp-full-record #1#))
    (tags "llvm")
    (buffer-name . "*eww*")
    (buffer-name . "*eww*")
    (front-context-string . " \nLLVM Logo\n\nNav")
    (rear-context-string)
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 3)
    (time 24802 9654 466466 693000)
    (created 24798 48478 675787 185000)
    (position . 1)
    (location . "https://llvm.org/docs/CMake.html")
    (handler . bmkp-jump-eww))
#1=(#("lldb" 0 4
      (bmkp-full-record #1#))
    (buffer-name . "*Bookmark List*")
    (visits . 0)
    (time . #2=(24798 46817 227522 423000))
    (created . #2#)
    (position . 306)
    (filename . "   - no file -")
    (bookmark-list
     (last-sort-comparer
      (bmkp-info-node-name-cp bmkp-gnus-cp bmkp-url-cp bmkp-local-file-type-cp)
      bmkp-alpha-p)
     (last-reverse-sort-p)
     (last-reverse-multi-sort-p)
     (last-bmenu-filter-function . bmkp-regexp-filtered-tags-alist-only)
     (last-bmenu-filter-pattern . "lldb")
     (last-bmenu-omitted-bookmarks)
     (last-bmenu-title . "Bookmarks with Tags Matching Regexp `lldb'")
     (last-bmenu-toggle-filenames . t))
    (handler . bmkp-jump-bookmark-list))
#1=(#("straight-root" 0 13
      (bmkp-full-record #1#))
    (tags "straight")
    (buffer-name . "straight")
    (front-context-string . "build\n  -rw-r--r")
    (rear-context-string . " Jul  1 11:07   ")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 4)
    (time 24806 1663 207093 742000)
    (created 24798 46040 78086 240000)
    (position . 228)
    (filename . "/home/rgr/.emacs.d/straight/")
    (dired-directory . "~/.emacs.d/straight/")
    (dired-marked)
    (dired-switches . "-al")
    (dired-subdirs)
    (dired-hidden-dirs)
    (handler . bmkp-jump-dired))
#1=(#("straight" 0 8
      (bmkp-full-record #1#))
    (annotation)
    (tags)
    (buffer-name . "*Bookmark List*")
    (visits . 2)
    (time 24806 1655 237216 336000)
    (created 24798 46084 406101 719000)
    (position . 159)
    (filename . "   - no file -")
    (bookmark-list
     (last-sort-comparer
      (bmkp-info-node-name-cp bmkp-gnus-cp bmkp-url-cp bmkp-local-file-type-cp)
      bmkp-alpha-p)
     (last-reverse-sort-p)
     (last-reverse-multi-sort-p)
     (last-bmenu-filter-function . bmkp-regexp-filtered-tags-alist-only)
     (last-bmenu-filter-pattern . "straight")
     (last-bmenu-omitted-bookmarks)
     (last-bmenu-title . "Bookmarks with Tags Matching Regexp `straight'")
     (last-bmenu-toggle-filenames . t))
    (handler . bmkp-jump-bookmark-list))
#1=(#("Getting Familar with LLVM IR" 0 28
      (bmkp-full-record #1#))
    (tags "llvm-ir" "llvm")
    (buffer-name . "*eww*")
    (buffer-name . "*eww*")
    (front-context-string . "\nGetting Familar")
    (rear-context-string . "tact Us Github \n")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 0)
    (time . #2=(24798 45248 557757 162000))
    (created . #2#)
    (position . 67)
    (location . "https://freecompilercamp.org/llvm-ir/")
    (handler . bmkp-jump-eww))
#1=(#("llvm-tutorial" 0 13
      (bmkp-full-record #1#))
    (tags "tutorial"
          #("project" 0 7
            (face nil)))
    (buffer-name . "llvm-tutorial")
    (front-context-string . "hello.c\n  -rwxr-")
    (rear-context-string . " Jul  1 19:05   ")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 11)
    (time 24823 53237 585457 503000)
    (created 24798 43912 378264 874000)
    (position . 340)
    (filename . "/home/rgr/development/projects/C/llvm-tutorial/")
    (dired-directory . "~/development/projects/C/llvm-tutorial/")
    (dired-marked)
    (dired-switches . "-al")
    (dired-subdirs)
    (dired-hidden-dirs)
    (handler . bmkp-jump-dired))
#1=(#("Affe" 0 4
      (bmkp-full-record #1#))
    (tags)
    (buffer-name . "*Affe - fuzzy grep*")
    (front-context-string . "\naffe.el - Async")
    (rear-context-string . "ion,  Up: (dir)\n")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 5)
    (time 24823 51386 934602 182000)
    (created 24798 42465 684258 671000)
    (position . 276)
    (filename . "/home/rgr/.emacs.d/straight/build/affe/affe")
    (info-node . "Top")
    (handler . Info-bookmark-jump)
    (defaults "(affe) Top" "affe" "Top"))
#1=(#("config-files" 0 12
      (bmkp-full-record #1#))
    (buffer-name . "*Bookmark List*")
    (visits . 2)
    (time 24823 52483 587517 728000)
    (created 24798 18614 719581 713000)
    (position . 155)
    (filename . "   - no file -")
    (bookmark-list
     (last-sort-comparer
      (bmkp-info-node-name-cp bmkp-gnus-cp bmkp-url-cp bmkp-local-file-type-cp)
      bmkp-alpha-p)
     (last-reverse-sort-p)
     (last-reverse-multi-sort-p)
     (last-bmenu-filter-function . bmkp-regexp-filtered-tags-alist-only)
     (last-bmenu-filter-pattern . "config")
     (last-bmenu-omitted-bookmarks)
     (last-bmenu-title . "Bookmarks with Tags Matching Regexp `config'")
     (last-bmenu-toggle-filenames . t))
    (handler . bmkp-jump-bookmark-list))
#1=(#("llvm" 0 4
      (bmkp-full-record #1#))
    (buffer-name . "*Bookmark List*")
    (visits . 6)
    (time 24823 51173 574310 57000)
    (created 24798 17181 520679 655000)
    (position . 151)
    (filename . "   - no file -")
    (bookmark-list
     (last-sort-comparer
      (bmkp-info-node-name-cp bmkp-gnus-cp bmkp-url-cp bmkp-local-file-type-cp)
      bmkp-alpha-p)
     (last-reverse-sort-p)
     (last-reverse-multi-sort-p)
     (last-bmenu-filter-function . bmkp-regexp-filtered-tags-alist-only)
     (last-bmenu-filter-pattern . "llvm")
     (last-bmenu-omitted-bookmarks)
     (last-bmenu-title . "Bookmarks with Tags Matching Regexp `llvm'")
     (last-bmenu-toggle-filenames . t))
    (handler . bmkp-jump-bookmark-list))
#1=(#("LLDB(1)" 0 7
      (bmkp-full-record #1#))
    (annotation)
    (tags "llvm" "lldb")
    (buffer-name . "*Man 1 lldb-11*")
    (front-context-string . "LLDB(1)         ")
    (rear-context-string)
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 2)
    (time 24802 13568 233619 557000)
    (created 24802 10743 722945 749000)
    (position . 1)
    (location . "man 1 lldb-11")
    (man-args . "1 lldb-11")
    (handler . Man-bookmark-jump))
#1=(#("Building — The LLDB Debugger" 0 28
      (bmkp-full-record #1#))
    (tags "lldb" "llvm")
    (bmkp-temp)
    (buffer-name . "*eww*")
    (buffer-name . "*eww*")
    (front-context-string . " \nBuilding¶\n\n* G")
    (rear-context-string)
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 21)
    (time 24802 13560 664886 836000)
    (created 24798 11306 586027 293000)
    (position . 1)
    (location . "https://lldb.llvm.org/resources/build.html")
    (handler . bmkp-jump-eww))
#1=(#("Getting Started with the LLVM System — LLVM 12 documentation" 0 60
      (bmkp-full-record #1#))
    (tags "llvm")
    (buffer-name . "*eww*")
    (buffer-name . "*eww*")
    (front-context-string . " An Example Usin")
    (rear-context-string . "w to use them.\n\n")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 17)
    (time 24802 13596 20492 290000)
    (created 24798 7624 143076 248000)
    (position . 36623)
    (location . "https://llvm.org/docs/GettingStarted.html#an-example-using-the-llvm-tool-chain")
    (handler . bmkp-jump-eww))
#1=(#("Python Reference — The LLDB Debugger" 0 36
      (bmkp-full-record #1#))
    (annotation)
    (tags "python" "llvm" "lldb")
    (buffer-name . "*eww*")
    (buffer-name . "*eww*")
    (front-context-string . "\nThere is a long")
    (rear-context-string . "its operations.\n")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 27)
    (time 24802 13564 642140 487000)
    (created 24796 5051 564874 219000)
    (position . 19474)
    (location . "https://lldb.llvm.org/use/python-reference.html")
    (handler . bmkp-jump-eww))
#1=(#("(emacs) Top" 0 11
      (bmkp-full-record #1#))
    (time 24823 51389 90691 496000)
    (visits . 1)
    (front-context-string . "\nThe Emacs Edito")
    (rear-context-string . "rib,  Up: (dir)\n")
    (position . 1141)
    (filename . "/home/rgr/development/projects/emacs/emacs/info/emacs")
    (info-node . "Top")
    (handler . Info-bookmark-jump))
#1=(#("udemy" 0 5
      (bmkp-full-record #1#))
    (time 24798 49457 741090 822000)
    (visits . 1)
    (filename . "~/development/education/Udemy/UdemyCpp/1_CppGrundlagen/Main.cc")
    (front-context-string . "          i++;\n ")
    (rear-context-string . "<10;i++)\n     {\n")
    (position . 1471))
#1=(#("extensions" 0 10
      (bmkp-full-record #1#))
    (time 24798 18090 908498 47000)
    (visits . 1)
    (filename . "~/.emacs.d/var/dap/extensions/")
    (front-context-string)
    (rear-context-string . " Jun  9 14:08   ")
    (position . 223))
#1=(#(".vscode" 0 7
      (bmkp-full-record #1#))
    (time 24798 12223 533840 235000)
    (visits . 0)
    (filename . "~/.vscode/")
    (front-context-string)
    (rear-context-string . " 8. Jun 20:37   ")
    (position . 236))
#1=(#("UdemyCpp" 0 8
      (bmkp-full-record #1#))
    (annotation)
    (tags "current" "project")
    (buffer-name . "UdemyCpp")
    (front-context-string . "Computerspiel1\n ")
    (rear-context-string . " Jul  7 10:38   ")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 4)
    (time 24823 53238 775980 128000)
    (created 24806 4684 599854 7000)
    (position . 1904)
    (filename . "/home/rgr/development/education/Udemy/UdemyCpp/")
    (dired-directory . "~/development/education/Udemy/UdemyCpp/")
    (dired-marked)
    (dired-switches . "-al")
    (dired-subdirs)
    (dired-hidden-dirs)
    (handler . bmkp-jump-dired))
#1=(#("swaymsg - Send messages to a running instance of sway over the IPC" 0 66
      (bmkp-full-record #1#))
    (front-context-string . "swaymsg(1)      ")
    (rear-context-string)
    (position . 1)
    (location .
              #("man 1 swaymsg" 6 13
                (help-echo "Send messages to a running instance of sway over the IPC socket.")))
    (man-args .
              #("1 swaymsg" 2 9
                (help-echo "Send messages to a running instance of sway over the IPC socket.")))
    (handler . Man-bookmark-jump))
#1=(#("steamapps" 0 9
      (bmkp-full-record #1#))
    (filename . "~/.steam/steam/steamapps/")
    (front-context-string . "appmanifest_1113")
    (rear-context-string . "96 May 11 11:07 ")
    (position . 218))
#1=(#("jq - Command-line JSON processor" 0 32
      (bmkp-full-record #1#))
    (front-context-string . "SYNOPSIS\n       ")
    (rear-context-string . "JSON processor\n\n")
    (position . 127)
    (location . "man -a jq")
    (man-args . "-a jq")
    (handler . Man-bookmark-jump))
#1=(#("sway" 0 4
      (bmkp-full-record #1#))
    (filename . "~/.config/sway/")
    (front-context-string)
    (rear-context-string . "38 May 18 14:01 ")
    (position . 210))
#1=(#("systemd" 0 7
      (bmkp-full-record #1#))
    (filename . "~/.config/systemd/")
    (front-context-string)
    (rear-context-string . "96 May 13 10:13 ")
    (position . 210))
#1=(#(".config" 0 7
      (bmkp-full-record #1#))
    (filename . "~/.config/")
    (front-context-string . "autostart\n  lrwx")
    (rear-context-string . "96 May  6 13:59 ")
    (position . 203))
#1=(#("(elisp) Defining Minor Modes" 0 28
      (bmkp-full-record #1#))
    (tags
     #("elisp" 0 5
       (face nil)))
    (time 24823 51391 84694 320000)
    (visits . 10)
    (front-context-string . "\n24.3.3 Defining")
    (rear-context-string . "Up: Minor Modes\n")
    (position . 1499424)
    (filename . "/home/rgr/development/projects/emacs/emacs/info/elisp")
    (info-node . "Defining Minor Modes")
    (handler . Info-bookmark-jump))
#1=(#("(elisp) Minor Modes" 0 19
      (bmkp-full-record #1#))
    (time 24823 51392 981133 864000)
    (visits . 3)
    (front-context-string . "\n24.3 Minor Mode")
    (rear-context-string . "des,  Up: Modes\n")
    (position . 1491062)
    (filename . "/home/rgr/development/projects/emacs/emacs/info/elisp")
    (info-node . "Minor Modes")
    (handler . Info-bookmark-jump))
#1=(#("lazy-lang-learn" 0 15
      (bmkp-full-record #1#))
    (annotation)
    (tags "project")
    (buffer-name . "lazy-lang-learn")
    (front-context-string . ".git\n  -rw-r--r-")
    (rear-context-string . " Jul  2 08:03   ")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 4)
    (time 24823 53236 425997 185000)
    (created 24798 50561 910873 294000)
    (position . 241)
    (filename . "/home/rgr/development/projects/emacs/lazy-lang-learn/")
    (dired-directory . "~/development/projects/emacs/lazy-lang-learn/")
    (dired-marked)
    (dired-switches . "-al")
    (dired-subdirs)
    (dired-hidden-dirs)
    (handler . bmkp-jump-dired))
#1=(#(".steam" 0 6
      (bmkp-full-record #1#))
    (filename . "~/.steam/")
    (front-context-string . "bin -> /home/rgr")
    (rear-context-string . "22 May 11 22:46 ")
    (position . 201))
#1=(#(".local" 0 6
      (bmkp-full-record #1#))
    (filename . "~/.local/")
    (front-context-string)
    (rear-context-string . "96 May 11 14:10 ")
    (position . 201))
#1=(#("native" 0 6
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/eln-cache/")
    (front-context-string . "28.0.50-33806cd2")
    (rear-context-string . "12 May 11 15:02 ")
    (position . 217))
#1=(#("eln-cache" 0 9
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/eln-cache/")
    (front-context-string . "28.0.50-33806cd2")
    (rear-context-string . "12 May 11 15:02 ")
    (position . 217))
#1=(#("init.el" 0 7
      (bmkp-full-record #1#))
    (end-position . 1184)
    (time 24804 45 671963 158000)
    (visits . 0)
    (filename . "~/.emacs.d/init.el")
    (front-context-string . "sp\" no-littering")
    (rear-context-string . "d-file-name \"eli")
    (position . 1184))
#1=(#("(elisp) Composite Types" 0 23
      (bmkp-full-record #1#))
    (tags "elisp")
    (time 24823 51926 757131 746000)
    (visits . 10)
    (front-context-string . "     the choices")
    (rear-context-string . "omatically from\n")
    (position . 801325)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Composite Types")
    (handler . Info-bookmark-jump))
#1=(#("(elisp) Quoting" 0 15
      (bmkp-full-record #1#))
    (time 24823 51928 740932 700000)
    (visits . 3)
    (front-context-string . "\n10.3 Quoting\n==")
    (rear-context-string . " Up: Evaluation\n")
    (position . 449831)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Quoting")
    (handler . Info-bookmark-jump))
#1=(#("(elisp) Top" 0 11
      (bmkp-full-record #1#))
    (tags)
    (time 24798 15553 408407 648000)
    (visits . 1)
    (front-context-string . "\nEmacs Lisp\n****")
    (rear-context-string . "ion,  Up: (dir)\n")
    (position . 1113)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Top")
    (handler . Info-bookmark-jump))
#1=(#("el-docstring-sap" 0 16
      (bmkp-full-record #1#))
    (time 24823 53240 440158 550000)
    (visits . 6)
    (tags "project")
    (filename . "~/development/projects/emacs/el-docstring-sap/")
    (front-context-string . "el-docstring-at-")
    (rear-context-string . "21. Apr 13:28   ")
    (position . 245))
#1=(#("(elisp) Property Lists" 0 22
      (bmkp-full-record #1#))
    (time 24798 16875 316581 242000)
    (visits . 2)
    (front-context-string . "A “property list")
    (rear-context-string . "==============\n\n")
    (position . 335406)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Property Lists")
    (handler . Info-bookmark-jump))
#1=(#("ctrlf.el" 0 8
      (bmkp-full-record #1#))
    (filename . "~/development/projects/emacs/ctrlf/ctrlf.el")
    (front-context-string . "(defun ctrlf-for")
    (rear-context-string . "\n;;;###autoload\n")
    (position . 50183))
#1=(#("(forge) Branching" 0 17
      (bmkp-full-record #1#))
    (front-context-string . "\n4.2 Branching\n=")
    (rear-context-string . "ing,  Up: Usage\n")
    (position . 18899)
    (filename . "/home/rgr/.emacs.d/etc/straight/build/forge/forge")
    (info-node . "Branching")
    (handler . Info-bookmark-jump))
#1=(#("(elisp) Interactive Call" 0 24
      (bmkp-full-record #1#))
    (tags "elisp")
    (time 24798 42720 713247 743000)
    (visits . 6)
    (front-context-string . "\n21.3 Interactiv")
    (rear-context-string . "p: Command Loop\n")
    (position . 1198814)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Interactive Call")
    (handler . Info-bookmark-jump))
#1=(#("hellopackage" 0 12
      (bmkp-full-record #1#))
    (end-position . 212)
    (time 24798 14535 537761 383000)
    (visits . 0)
    (filename . "~/development/education/lessons/python/helloworld/hellopackage/")
    (front-context-string . "..\n  -rw-r--r-- ")
    (rear-context-string . " 4. Apr 10:37   ")
    (position . 212))
#1=(#("helloworld root" 0 15
      (bmkp-full-record #1#))
    (end-position . 422)
    (time 24798 14537 950584 612000)
    (visits . 0)
    (filename . "~/development/education/lessons/python/helloworld/")
    (front-context-string . "main.py\n  drwxr-")
    (rear-context-string . " 3. Apr 22:27   ")
    (position . 422))
#1=(#("Fluent Python.pdf" 0 17
      (bmkp-full-record #1#))
    (filename . "~/Documents/Programming/Python/Fluent Python.pdf")
    (position . 1)
    (page . 32)
    (slice)
    (size . 1.9301587301587302)
    (origin 0.0 . 0.0)
    (handler . pdf-view-bookmark-jump-handler))
#1=(#("19-slicing.org" 0 14
      (bmkp-full-record #1#))
    (filename . "~/development/education/lessons/python/coreyschafer/19-slicing.org")
    (front-context-string)
    (rear-context-string . ", 5, 6, 7, 8.9]\n")
    (position . 1402))
#1=(#("python-lessons" 0 14
      (bmkp-full-record #1#))
    (filename . "~/development/education/lessons/python/")
    (front-context-string . "comprehensions.o")
    (rear-context-string . "6 26. Mär 23:47 ")
    (position . 197))
#1=(#("Python" 0 6
      (bmkp-full-record #1#))
    (filename . "~/development/projects/Python/")
    (front-context-string)
    (rear-context-string . "6 15. Mär 00:54 ")
    (position . 188))
#1=(#("org agenda files list" 0 21
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/etc/org/agenda-files.txt")
    (front-context-string . "~/.emacs.d/var/o")
    (rear-context-string)
    (position . 1))
#1=(#("inttobin.c" 0 10
      (bmkp-full-record #1#))
    (filename . "~/development/projects/C/inttobin/inttobin.c")
    (front-context-string . "\n	unsigned int b")
    (rear-context-string . " num, char *p)\n{")
    (position . 154))
#1=(#("inttobin" 0 8
      (bmkp-full-record #1#))
    (filename . "~/development/projects/C/inttobin/")
    (front-context-string . "inttobin.c\n  -rw")
    (rear-context-string . "5 20. Nov 19:43 ")
    (position . 781))
#1=(#("C" 0 1
      (bmkp-full-record #1#))
    (filename . "~/development/projects/C/")
    (front-context-string . "inttobin\n  drwxr")
    (rear-context-string . "6 26. Feb 10:18 ")
    (position . 298))
#1=(#("projects" 0 8
      (bmkp-full-record #1#))
    (annotation)
    (tags)
    (buffer-name . "*Bookmark List*")
    (visits . 5)
    (time 24823 53289 885661 905000)
    (created 24798 44043 528761 763000)
    (position . 151)
    (filename . "   - no file -")
    (bookmark-list
     (last-sort-comparer
      (bmkp-info-node-name-cp bmkp-gnus-cp bmkp-url-cp bmkp-local-file-type-cp)
      bmkp-alpha-p)
     (last-reverse-sort-p)
     (last-reverse-multi-sort-p)
     (last-bmenu-filter-function . bmkp-regexp-filtered-tags-alist-only)
     (last-bmenu-filter-pattern . "proj")
     (last-bmenu-omitted-bookmarks)
     (last-bmenu-title . "Bookmarks with Tags Matching Regexp `proj'")
     (last-bmenu-toggle-filenames . t))
    (handler . bmkp-jump-bookmark-list))
#1=(#("(emacs) Regexps" 0 15
      (bmkp-full-record #1#))
    (tags)
    (time 24798 15554 588361 784000)
    (visits . 0)
    (front-context-string . "\n15.6 Syntax of ")
    (rear-context-string . "ch,  Up: Search\n")
    (position . 379636)
    (filename . "/usr/share/info/emacs/emacs")
    (info-node . "Regexps")
    (handler . Info-bookmark-jump))
#1=(#("orgfiles" 0 8
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/var/org/orgfiles/")
    (front-context-string . "ardour.org\n  -rw")
    (rear-context-string . "35 Dec 29 16:56 ")
    (position . 226))
#1=(#("(org) Global and local cycling" 0 30
      (bmkp-full-record #1#))
    (front-context-string . "\n2.3.1 Global an")
    (rear-context-string . "ibility cycling\n")
    (position . 41218)
    (filename . "/usr/share/info/emacs/org")
    (info-node . "Global and local cycling")
    (handler . Info-bookmark-jump))
#1=(#("(org) Visibility cycling" 0 24
      (bmkp-full-record #1#))
    (front-context-string . "\n* Global and lo")
    (rear-context-string . "======\n\n* Menu:\n")
    (position . 40890)
    (filename . "/usr/share/info/emacs/org")
    (info-node . "Visibility cycling")
    (handler . Info-bookmark-jump))
#1=(#("org motion movement" 0 19
      (bmkp-full-record #1#))
    (front-context-string . "\nThe following c")
    (rear-context-string . "tion\n==========\n")
    (position . 45861)
    (filename . "/usr/share/info/emacs/org")
    (info-node . "Motion")
    (handler . Info-bookmark-jump))
#1=(#("tmp" 0 3
      (bmkp-full-record #1#))
    (filename . "~/tmp/")
    (front-context-string . "158c9c7b25afac14")
    (rear-context-string . "2 16. Feb 14:04 ")
    (position . 178))
#1=(#("llvm-project" 0 12
      (bmkp-full-record #1#))
    (tags "llvm" "llvm-ir")
    (end-position . 229)
    (time 24823 51436 233252 176000)
    (visits . 6)
    (filename . "~/bin/thirdparty/llvm-project/")
    (front-context-string . ".arcconfig\n  -rw")
    (rear-context-string . "18. Feb 17:16   ")
    (position . 229))
#1=(#(".git" 0 4
      (bmkp-full-record #1#))
    (filename . "~/bin/thirdparty/llvm-project/.git/")
    (front-context-string . "branches\n  -rw-r")
    (rear-context-string . "18. Feb 17:09   ")
    (position . 217))
#1=(#("thirdparty" 0 10
      (bmkp-full-record #1#))
    (filename . "~/bin/thirdparty/")
    (front-context-string . "acpilight\n  lrwx")
    (rear-context-string . "6 20. Dez 15:06 ")
    (position . 182))
#1=(#("xresources" 0 10
      (bmkp-full-record #1#))
    (filename . "~/Dropbox/homefiles/linux-config.org")
    (front-context-string . "ources\n   #+begi")
    (rear-context-string . "d_src\n** ~/.Xres")
    (position . 6635))
#1=(#("lessons" 0 7
      (bmkp-full-record #1#))
    (filename . "~/development/education/lessons/")
    (front-context-string . "advice.org\n  drw")
    (rear-context-string . "8 25. Jan 19:35 ")
    (position . 193))
#1=(#("Music" 0 5
      (bmkp-full-record #1#))
    (filename . "~/Music/")
    (front-context-string . "05 Robin Thicke ")
    (rear-context-string . "13 Aug 31  2014 ")
    (position . 223))
#1=(#("(cl) Structures" 0 15
      (bmkp-full-record #1#))
    (time 24798 13662 908937 692000)
    (visits . 0)
    (front-context-string . "or lists upon re")
    (rear-context-string . "res as vectors (")
    (position . 153481)
    (filename . "/usr/share/info/emacs/cl")
    (info-node . "Structures")
    (handler . Info-bookmark-jump))
#1=(#("Dropbox" 0 7
      (bmkp-full-record #1#))
    (filename . "~/Dropbox/")
    (front-context-string . "homefiles\n  drwx")
    (rear-context-string . "96 Jan 25 14:56 ")
    (position . 477))
#1=(#("(elisp) Edebug" 0 14
      (bmkp-full-record #1#))
    (tags "elisp")
    (time 24798 42720 26819 82000)
    (visits . 8)
    (front-context-string . "\n18.2 Edebug\n===")
    (rear-context-string . "  Up: Debugging\n")
    (position . 952719)
    (filename . "/usr/share/info/emacs/elisp")
    (info-node . "Edebug")
    (handler . Info-bookmark-jump))
#1=(#("vollfilm-new" 0 12
      (bmkp-full-record #1#))
    (end-position . 244)
    (time 24798 14539 157807 262000)
    (visits . 0)
    (filename . "~/development/projects/vollfilm-new/")
    (front-context-string . "apache2\n  drwxr-")
    (rear-context-string . "96 Dec 28 21:21 ")
    (position . 244))
#1=(#("development" 0 11
      (bmkp-full-record #1#))
    (filename . "~/development/")
    (front-context-string . "arduino\n  drwxr-")
    (rear-context-string . "96 Dec 28 21:20 ")
    (position . 206))
#1=(#("ctrlf" 0 5
      (bmkp-full-record #1#))
    (filename . "~/development/projects/emacs/ctrlf/")
    (front-context-string . "CHANGELOG.md\n  d")
    (rear-context-string . " 9. Apr 22:40   ")
    (position . 233))
#1=(#("debus-services" 0 14
      (bmkp-full-record #1#))
    (filename . "/usr/share/dbus-1/services/")
    (front-context-string . "ca.desrt.dconf-e")
    (rear-context-string . "93 Sep 15 20:42 ")
    (position . 216))
#1=(#("etc-hosts" 0 9
      (bmkp-full-record #1#))
    (annotation)
    (tags)
    (filename . "/sudo:root@localhost:/etc/hosts")
    (buffer-name . "/sudo:root@localhost:/hosts")
    (front-context-string . "\nff02::2 ip6-all")
    (rear-context-string . "::1 ip6-allnodes")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 1)
    (time 24802 47784 954567 473000)
    (created 24802 47770 823301 830000)
    (position . 197))
#1=(#("etc" 0 3
      (bmkp-full-record #1#))
    (filename . "/etc/")
    (front-context-string . "acpi\n  -rw-r--r-")
    (rear-context-string . "6 27. Dez 23:37 ")
    (position . 181))
#1=(#("hosts" 0 5
      (bmkp-full-record #1#))
    (end-position . 172)
    (time 24802 47759 905241 321000)
    (visits . 0)
    (filename . "~/.emacs.d/etc/hosts/")
    (front-context-string . "..\n  drwxr-xr-x ")
    (rear-context-string . "6 11. Jan 10:20 ")
    (position . 172))
#1=(#("linux-config" 0 12
      (bmkp-full-record #1#))
    (tags "config")
    (time 24823 52506 480002 447000)
    (visits . 20)
    (filename . "~/Dropbox/homefiles/linux-config.org")
    (front-context-string . "d\n**  ~/.profile")
    (rear-context-string . "]\n\n* Bash relate")
    (position . 19971))
#1=(#("emacs-var" 0 9
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/var/")
    (front-context-string . "auto-save\n  drwx")
    (rear-context-string . "6 11. Jan 00:42 ")
    (position . 196))
#1=(#("emacs-etc" 0 9
      (bmkp-full-record #1#))
    (end-position . 453)
    (time 24804 53717 327281 767000)
    (visits . 1)
    (filename . "~/.emacs.d/etc/")
    (front-context-string . "elisp\n  drwxr-xr")
    (rear-context-string . "6 11. Jan 10:20 ")
    (position . 453))
#1=(#("home" 0 4
      (bmkp-full-record #1#))
    (time 24798 51542 64183 698000)
    (visits . 0)
    (filename . "~/")
    (front-context-string . "Dropbox\n  drwxrw")
    (rear-context-string . "6 12. Jan 23:39 ")
    (position . 2783))
#1=(#("Xsession.d" 0 10
      (bmkp-full-record #1#))
    (filename . "/etc/X11/Xsession.d/")
    (front-context-string . ":\n  insgesamt 80")
    (rear-context-string . "c/X11/Xsession.d")
    (position . 22))
#1=(#("auth" 0 4
      (bmkp-full-record #1#))
    (filename . "~/.gnupg/auth/")
    (front-context-string . "authmbsync.gpg\n ")
    (rear-context-string . "4  7. Jan 05:24 ")
    (position . 344))
#1=(#(".gnupg" 0 6
      (bmkp-full-record #1#))
    (filename . "~/.gnupg/")
    (front-context-string . "auth\n  drwx-----")
    (rear-context-string . "6  7. Jan 05:20 ")
    (position . 174))
#1=(#("bin" 0 3
      (bmkp-full-record #1#))
    (filename . "~/bin/")
    (front-context-string . "acpi-powerstate-")
    (rear-context-string . "64 Dec 27 13:40 ")
    (position . 202))
#1=(#("x11-xsession" 0 12
      (bmkp-full-record #1#))
    (filename . "/etc/X11/Xsession")
    (front-context-string . "\nUSERXSESSION=$H")
    (rear-context-string . "c/X11/Xsession.d")
    (position . 1643))
#1=(#("custom.el" 0 9
      (bmkp-full-record #1#))
    (filename . "~/.emacs.d/custom.el")
    (front-context-string . "(custom-set-vari")
    (rear-context-string)
    (position . 1))
#1=(#("elisp" 0 5
      (bmkp-full-record #1#))
    (annotation)
    (tags)
    (buffer-name . "elisp")
    (front-context-string . "rgr-programming.")
    (rear-context-string . " Jul  6 23:56   ")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 0)
    (time . #2=(24804 53721 672666 501000))
    (created . #2#)
    (position . 834)
    (filename . "/home/rgr/.emacs.d/etc/elisp/")
    (dired-directory . "~/.emacs.d/etc/elisp/")
    (dired-marked)
    (dired-switches . "-al")
    (dired-subdirs)
    (dired-hidden-dirs)
    (handler . bmkp-jump-dired))
#1=(#("emacs" 0 5
      (bmkp-full-record #1#))
    (tags "project")
    (end-position . 800)
    (time 24823 53331 728675 790000)
    (visits . 3)
    (filename . "~/.emacs.d/")
    (front-context-string . "etc\n  drwxr-xr-x")
    (rear-context-string . "6 29. Apr 11:56 ")
    (position . 800))
)
